// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MoviesApp.Migrations
{
    [DbContext(typeof(MovieContext))]
    [Migration("20220308152417_movie")]
    partial class movie
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Titanik"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Spider-Man"
                        });
                });

            modelBuilder.Entity("MovieDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<string>("MovieYear")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Ratings")
                        .HasColumnType("double");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.ToTable("MovieDetails");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Detail = "Güzel film",
                            Director = "Nuri Bilge Ceylan",
                            Language = "Tr",
                            MovieId = 1,
                            MovieYear = "1998",
                            Ratings = 7.5,
                            Type = 2
                        },
                        new
                        {
                            Id = 2,
                            Detail = "Muhammed şeften öneriler",
                            Director = "Peter Parker",
                            Language = "Eng",
                            MovieId = 2,
                            MovieYear = "1990",
                            Ratings = 8.0,
                            Type = 3
                        });
                });

            modelBuilder.Entity("MovieDetail", b =>
                {
                    b.HasOne("Movie", "Movie")
                        .WithMany("movieDetail")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("Movie", b =>
                {
                    b.Navigation("movieDetail");
                });
#pragma warning restore 612, 618
        }
    }
}
